---
title: "Test quanTIseq deconvolution"
output: html_notebook
---

```{r setup}
source("./quanTIseq_decon.R")

library(tidyverse)
library(assertthat)
library(magrittr)
library(pheatmap)
```

# Using the example file provided by quanTIseq
```{r}
expr_mat = read_tsv("examples/quanTIseqTest_gene_tpm.txt") %>% column_to_rownames("GENE")

res = quantiseq_decon(expr_mat)
```

Assure the result is as expected

```{r}
res_expected = read_tsv("./examples/quanTIseqTest_cell_fractions.txt") 

res2 = res %>% as_tibble() %>% select(-Sample) %>% as.matrix()
res_expected2 = res_expected %>% column_to_rownames("Sample") %>% as.matrix()

assert_that(all.equal(res2, res_expected2))
```

# Using some other data (cell-type specific gene expression from fantom5)
```{r}
f5_mat = read_tsv("examples/f5_samples.tsv") %>% column_to_rownames("gene_symbol")
f5_res = quantiseq_decon(f5_mat) 
f5_res %<>% as_tibble() %>% select(-Sample) %>% as.matrix()
pheatmap(f5_res, cluster_rows = FALSE, cluster_cols = FALSE)
```